### ISSUE TITLE
Add argument for silent outputwhen running flow-remove-types

### ISSUE THREAD

**Issue by moberemk** [flowtype/flow-remove-types#27]
Something I'd like to see is the ability to compress or suppress the output when running the command-line tool as not to fill my terminal with copy commands. It's almost never useful information in the write code -> run -> test -> write code cycle and produces a lot of excess output in my terminal.

I could pipe the output to `/dev/null` but honestly I'd rather avoid doing that if possible because I don't want to lose access to the exit code for the system.

Any thoughts?

**Comment by leebyron** [comment]
Sounds reasonable. How about --quiet or -q

**Comment by moberemk** [comment]
That's intuitive yeah; you could also go for -s --silent to match npm
behaviour?

**Comment by leebyron** [comment]
Ah, interesting. I was pulling from git which uses -q --quiet.

**Comment by leebyron** [comment]
Choice seems fairly arbitrary, so I googled for "cli --quiet" and "cli --silent" and see more results for --quiet, also -q is a less common letter, so less likely to conflict if we ever decide to add something that wants to use the -s?

**Comment by moberemk** [comment]
Yep, that works. Just suggesting it in case it made more sense to match
node tooling. Either works for my purposes though.

**Comment by moberemk** [comment]
Awesome! Thanks a bunch for adding this man, I'll update my deps in the
morning.
