### ISSUE TITLE
Is it suitable for production code ?

### ISSUE THREAD

**Issue by thomasthiebaud** [flowtype/flow-remove-types#29]
I would like to use flow on an existing project which is not using babel at all.

Is it safe to use `flow-remove-types` for production code ? Is there any things to consider before ?

**Comment by leebyron** [comment]
It's definitely suitable for production code, however note that using the Require Hook is suggested to be used only in development (https://github.com/flowtype/flow-remove-types#use-the-require-hook) - the same is true of Babel's Require Hook.

If you are transforming code before running it in production, then you should be in good shape.
