### ISSUE TITLE
how to output all file (include package.json and others )

### ISSUE THREAD

**Issue by CNBlackJ** [flowtype/flow-remove-types#38]
@leebyron 
Before deploying to product environment, I want to remove flow type.
Using `flow-remove-types --out-dir in out` , it have not include such file.

**Comment by leebyron** [comment]
`flow-remove-types` only operates on source files. It is not a generic replacement for `cp`. If you wish to copy over other files in your deployment script, you'll need to do that separately.

**Comment by NE-SmallTown** [comment]
Could we add a option `--copy-files`  just like it works in Babel?

**Comment by joshuaquek** [comment]
Yes, could we simply implement what @NE-SmallTown suggested?

**Comment by leebyron** [comment]
No, I’d rather not have this tool become a generic build tool - it’s specifically for removing flow types from files. `cp` is a great tool for copying files, especially with glob support and all the other awesomeness bash provides. Another alternative is gulp or make or some build runner which have a ton of file copying utilities.
