### ISSUE TITLE
flow-node repl functionality explanation

### ISSUE THREAD

**Issue by faizalpribadi** [flowtype/flow-remove-types#39]
Dear @leebyron 
In there's at documentation, `flow-node` repl not much explanation functionality of repl

```js
flow-node
var x: Array<number> = {undef: 'undef'}
undefined
x
{ undef: 'undef' }
```
`flow-node` repl does not throwing error like `flow` cli actually 😅

**Comment by leebyron** [comment]
The repl is a JavaScript interpreter which removes the types first. It does not run flow itself
