### ISSUE TITLE
all=true option in the flow configuration file option is being ignored

### ISSUE THREAD

**Issue by tech-no-crat** [flowtype/flow-remove-types#44]
I have project with an `src/` folder containing type-annotated javascript, and a `lib/` folder containing the final files. In the project's root directory I have a `.flowconfig` file with the `all=true` option in the `[options]` section, so that I don't have to specify the `//@flow` directive in the beginning of each file. And while this works when type-checking with flow, flow-remove-types still requires the `//@flow` directive in order to parse and compile the files properly.

I'm using flow-remove-types like this from the project's root folder: `flow-remove-types -d lib/ src/`.

**Comment by asci** [comment]
@tech-no-crat did you try to use option `--all` https://github.com/flowtype/flow-remove-types/blob/975c67bdbab9f2ef2cfd5817e4bb4e50b36d7b3d/index.js#L10 ?

**Comment by phillipj** [comment]
@asci thanks for the tip, passing `--all` did the trick for me 👍
