### ISSUE TITLE
code removed types has many whitespace not removed

### ISSUE THREAD

**Issue by xiaoping0x** [flowtype/flow-remove-types#49]
babel is better solution.

```sh
babel --plugins transform-flow-strip-types src -d src-remove-flowtypes
```

**Comment by TrySound** [comment]
Whitespaces can be removed
https://github.com/flowtype/flow-remove-types#pretty-transform
Babel is very slow.

**Comment by leebyron** [comment]
The whitespace left behind is very much intentional - it allows this transform to be applied *without need for source maps*. Optionally, the white-space can be removed.
