### ISSUE TITLE
If source = destination, it deletes the file!

### ISSUE THREAD

**Issue by raynor85** [flowtype/flow-remove-types#51]
I just run: flow-remove-types pages/login.js > pages/login.js
Luckily I have version control, otherwise it would be a disaster

**Comment by lydell** [comment]
This is a general command line gotcha. It is not special to flow-remove-types. See https://superuser.com/questions/597244/why-does-redirecting-the-output-of-a-file-to-itself-produce-a-blank-file

Use this instead: `flow-remove-types pages/login.js --out-file pages/login.js`

**Comment by MarkSMT** [comment]
Mention this in the docs please as i can imagine many people will encounter this.. Just lost an hours work 😢

**Comment by lydell** [comment]
@MarkSMT Why the :-1: reaction? I was just trying to help 😞

**Comment by MarkSMT** [comment]
@lydell I'm just an emotional guy 😉  😘
