### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by clintwood** [flowtype/flow-remove-types#65]
@leebyron, I see last release was back in Oct 18, 2017.

If accepted I'd be keen to make use of `--copy-source` feature submitted in PR #64

**Comment by alexschrod** [comment]
Project appears to be dead.

**Comment by clintwood** [comment]
@alexschrod Is there an alternative to this, I'm not aware of one?

**Comment by alexschrod** [comment]
I switched to using Babel with `babel-preset-flow` and haven't run into
issues with that one yet. https://flow.org/en/docs/tools/babel/

Psst: If using npm at least, use `@babel/preset-flow` instead
of `babel-preset-flow`.

**Comment by clintwood** [comment]
@alexschrod, Thanks!

**Comment by clintwood** [comment]
@alangpierce, **Surcrase** looks great!  Will give it a try.  Interestingly you've hit my requirement 100% - Transform non-standard extensions of modern JS to just modern JS - _FAST_.  Nice!

**Comment by motiz88** [comment]
Hey everyone, I'd like to apologise for the radio silence. I'm working on a v2 release that will upgrade the parser, stay in sync with the main Flow repo and address the outstanding bugs.

FWIW I think the lightweight approach that this package takes is still one of the best ways to strip Flow types - _if_ that's truly all you need. Stripping types using the Babel preset might indeed be the way to go if you're already using Babel for other things.

**Comment by clintwood** [comment]
I've switched to Typescript so you are welcome to close this issue.  Thanks.

**Comment by chapati23** [comment]
@motiz88 i know you're probably doing this in your freetime, so thanks for working on it at all :)

still need to ask, tho: any updates soon? really don't wanna introduce the whole babel toolchain just for stripping flow types but it's becoming a serious impediment for us at this stage

**Comment by motiz88** [comment]
@chapati23 I have the pieces all lined up - some urgent work on another project took precedence, hence the delay, but v2 is still coming very soon. I'll share a timeline when I can definitely commit to it.

**Comment by motiz88** [comment]
We've just published v2.99.0 of both `flow-remove-types` and `flow-node`. Future releases will be aligned with Flow releases (e.g. v2.99.0 ↔ Flow 0.99.0) and will always use the latest version of the Flow parser for maximum compatibility.

The code has now [moved](https://github.com/facebook/flow/tree/master/packages/flow-remove-types) to the main Flow repo, and this separate repo will be archived soon; please use the Flow issue tracker for any further discussion.

**Comment by chapati23** [comment]
Thanks for the update @motiz88, great to hear!
