### ISSUE TITLE
Generics are left behind on class method call and when constructing imported class

### ISSUE THREAD

**Issue by alexschrod** [flowtype/flow-remove-types#74]
I have this bit of code:

```
const comicImg = $('img[src*="/comics/"]');
...
const comicImage = comicImg.get<HTMLImageElement>(0);
let comicLinkUrl = (comicImage.src: any); // Put this cast here just to confirm that it otherwise works
```

`$(...)` returns the class type `JQuery`, which has the following definition of `get` on it:  `get<T: HTMLElement>(index: number): T;`

When running this through flow-remove-types, this comes out:

```
const comicImg = $('img[src*="/comics/"]');
...
const comicImage = comicImg.get<HTMLImageElement>(0);
let comicLinkUrl = (comicImage.src     ); // Put this cast here just to confirm that it otherwise works
```

Hey look, the generic type is still there in the function call! That can't be right, can it?

**Comment by alexschrod** [comment]
Apparently it's even worse than that. It also leaves generics behind on classes...

```
import constants from '../../../constants';
import { Event } from '../event';

class Foo {
    comicDataLoadingEvent: Event<number>;

    constructor() {
        this.comicDataLoadingEvent = new Event<number>(constants.comicdataLoadingEvent);
    }
}
```

Guess what the above ends up looking like in the output? Yup, you guessed it -- generics left behind:

```
import constants from '../../../constants';
import { Event } from '../event';

class Foo {
	                                     

    constructor() {
        this.comicDataLoadingEvent = new Event<number>(constants.comicdataLoadingEvent);
    }
}
```

**Comment by motiz88** [comment]
This is the same problem as https://github.com/flowtype/flow-remove-types/issues/76, and will be resolved in the next major release which will upgrade the parser to recognise this syntax.

**Comment by chapati23** [comment]
Still broken for me with react hooks. Screenshot of code _after_ `flow-remove-types` ran:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/117495/55962914-15022500-5c72-11e9-8ff1-ecddb3717a0e.png">

**Comment by motiz88** [comment]
Closing in favour of #89.
