### ISSUE TITLE
Add PropTypes from interface? 

### ISSUE THREAD

**Issue by MiroslavPetrik** [flowtype/flow-remove-types#83]
Would it be possible to transform existing interfaces to prop types definitions?

**Comment by motiz88** [comment]
Hi @MiroslavPetrik, unfortunately no, I think that would be far outside the scope of this tool. I suggest you look into community Babel plugins that do this, such as https://github.com/brigand/babel-plugin-flow-react-proptypes and https://github.com/atlassian/babel-plugin-react-flow-props-to-prop-types (note that I haven't tried them myself).
